### ISSUE TITLE
Dracthyr

### ISSUE THREAD

**Issue by gz2k2** [jyggen/BarberShopProfiles#3]
Dracthyr won't save / load correctly.
Dragonform and Human form are messed up on 2 different Toons

**Comment by jyggen** [comment]
This should be fixed in the latest version of the addon (1.1.0) by having separate profiles for the dragon- and the visage forms. Do note that profiles created in previous versions will still have this issue, so any existing profile will need to be re-saved in order the take advantage of this new feature.
